name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "src/embeddings_api/**"
      - "src/embeddings_client/**"
      - "Dockerfile"
      - "pyproject.toml"
      - "poetry.lock"
      - ".github/workflows/deploy.yaml"

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: destaquesgovbr/reusable-workflows/.github/workflows/cloud-run-deploy.yml@v2
    with:
      dockerfile: Dockerfile
      ar_repository: destaquesgovbr-embeddings-api
      image_name: embeddings-api
      cloud_run_service: destaquesgovbr-embeddings-api
      free_disk_space: true
